auto: true
server: true
pygments: true
permalink: none
baseurl: ""
oauth_client_id: 47be2cb6636861a8c77d
gatekeeper_url: "http://ec2-23-20-59-58.compute-1.amazonaws.com"
exclude:
- .gitignore
- README.md
