auto: true
server: true
pygments: true
permalink: none
baseurl: ""
oauth_client_id: c602a8bd54b1e774f864
gatekeeper_url: http://ec2-54-235-20-128.compute-1.amazonaws.com:8080
exclude:
- .gitignore
- README.md
