auto: true
server: true
pygments: true
permalink: none
baseurl: ""
oauth_client_id: 47be2cb6636861a8c77d
gatekeeper_url: http://ec2-54-235-20-128.compute-1.amazonaws.com:8080
exclude:
- .gitignore
- README.md
